# Generated by Django 6.1 on 2026-08-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudante',
            old_name='emai',
            new_name='email',
        ),
    ]
